server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/misadlondono/Locpropertie.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          search-paths: .

  security:
    user:
      name: root
      password: s3cr3t

